<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Beschreibung Kv' => 'Kursbeschreibung',
    'Beschreibung Mv' => 'Modulbeschreibung ',
    'Bis Kv' => 'Kurs bis',
    'Bis Mv' => 'Modul bis',
    'Deleted Ka' => 'Anmeldung gelöscht',
    'Deleted Kv' => 'Kurs gelöscht',
    'Id Ka' => 'AnmledungsID',
    'Id Kv' => 'KursID',
    'Id Mv' => 'ModulID',
    'Id Sudc' => '',
    'Id Sutu' => '',
    'Id Utkv' => '',
    'Iddc Ka' => '',
    'Idkv Ka' => '',
    'Idkv Mv' => '',
    'Idkv Sudc' => '',
    'Idkv Sutu' => '',
    'Idkv Utkv' => '',
    'Iduser Utkv' => '',
    'Send Sudc' => '',
    'Send Sutu' => '',
    'Sigdate Kv' => '',
    'Sigdate Mav' => '',
    'Sigid Kv' => '',
    'Sigid Mv' => '',
    'Titel Kv' => 'Kurstitel',
    'Titel Mv' => 'Modultitel',
    'Von Kv' => 'Kurs von',
    'Von Mv' => 'Modul von',
];
